services:
  qnetd:
    container_name: proxmox-qdevice
    image: bcleonard/proxmox-qdevice
    build: .
    ports:
      - "22:22"
      - "5403:5403"
    environment:
      - "NEW_ROOT_PASSWORD=CHANGEME"
    volumes:
      - /run/sshd
      - 192.168.178.9:/etc/corosync
    restart: unless-stopped
    hostname: qdevice.local
    networks: 
      vlan:
        ipv4_address: 192.168.178.11

networks:
 vlan:
    driver: macvlan
    driver_opts:
      parent: 192.168.178.7
    ipam:
       driver: default
       config:
        - subnet: "192.168.178.0/24"
          ip_range: "192.168.178.7/32"
          gateway: "192.168.178.7"
